[package]
name = "calculator-wasm-rust-pwa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.1"
egui_json_tree = "0.5.0"
serde_json = "1.0.115"
